#!/bin/sh
echo ""
echo "				Executing post-merge"
echo "				Starting CMake"
echo ""
if [ ! -d "buildx64" ]; then
	mkdir buildx64
fi
cd buildx64
cmake -C ../cmake_cache_x64.cmake -G "Visual Studio 14 2015 Win64" ../.
echo ""
echo "				CMake finished"
echo "				You can now live your life normally."
echo ""