set(SOLUTION_PLATFORM "x64" CACHE PATH "")
set(INCLUDE_DIRS "../../inc/" CACHE PATH "")
set(LIBS_DIRS "../../libs/x64" CACHE PATH "")
set(SDL_INCLUDE_DIR "../../inc/SDL" CACHE PATH "")
set(SDLMAIN_LIBRARY optimized "../../libs/x64/SDL2main" debug "../../libs/x64/SDL2maind" CACHE PATH "")
set(SDL_LIBRARY optimized "../../libs/x64/SDL2" debug "../../libs/x64/SDL2d" CACHE PATH "")
set(SDL_IMAGE_LIBRARY optimized "../../libs/x64/SDL2_image" debug "../../libs/x64/SDL2_imaged" CACHE PATH "")
set(SDL_IMAGE_INCLUDE_DIR "../../inc/SDL" CACHE PATH "")
set(SDL_TTF_LIBRARY optimized "../../libs/x64/SDL2_ttf" debug "../../libs/x64/SDL2_ttfd" CACHE PATH "")
set(SDL_TTF_INCLUDE_DIR "../../inc/SDL" CACHE PATH "")
set(FREETYPE_INCLUDE_DIR_freetype2 "../../inc/freetype" CACHE PATH "")
set(FREETYPE_INCLUDE_DIR_ft2build "../../inc/freetype" CACHE PATH "")
set(FREETYPE_LIBRARY optimized "../../libs/x64/freetype" debug "../../libs/x64/freetyped" CACHE PATH "")
set(GLEW_INCLUDE_DIR "../../inc/GL" CACHE PATH "")
set(GLEW_LIBRARY optimized "../../libs/x64/glew32" debug "../../libs/x64/glew32d" CACHE PATH "")
set(BULLET_INCLUDE_DIR "../../inc/bullet" CACHE PATH "")
set(BULLET_COLLISION_LIBRARY optimized "../../libs/x64/BulletDynamics" debug "../../libs/x64/BulletDynamics_Debug" CACHE PATH "")
set(BULLET_DYNAMICS_LIBRARY optimized "../../libs/x64/BulletCollision" debug "../../libs/x64/BulletCollision_Debug" CACHE PATH "")
set(BULLET_MATH_LIBRARY optimized "../../libs/x64/LinearMath" debug "../../libs/x64/LinearMath_Debug" CACHE PATH "")
set(BULLET_SOFTBODY_LIBRARY optimized "../../libs/x64/BulletSoftBody" debug "../../libs/x64/BulletSoftBody_Debug" CACHE PATH "")