#!/bin/sh
echo ""
echo "				Executing post-merge"
echo "				Starting CMake"
echo ""
if [ ! -d "build//win64" ]; then
	mkdir build//win64
fi
cd build//win64
cmake -C ../../cmake_cache_x64.cmake -G "Visual Studio 14 2015 Win64" ../.
echo ""
echo "				CMake finished"
echo "				You can now live your life normally."
echo ""