set(CMAKE_CONFIGURATION_TYPES Debug MinSizeRel Release RelWithDebInfo DebugWithMemoryTracking Gcc)
set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES}" CACHE STRING "Added DebugWithMemoryTracking configuration" FORCE)

set(CMAKE_CXX_FLAGS "/DMSVC /W4 /WX /Zc:wchar_t- /GR /EHsc" CACHE STRING "c++ compiler flags" FORCE)
set(CMAKE_CXX_FLAGS_DEBUG "/D_DEBUG /FR /MDd /ZI /Ob0 /Od /RTC1" CACHE STRING "c++ debug compiler flags" FORCE)
set(CMAKE_CXX_FLAGS_DEBUGWITHMEMORYTRACKING "/D_DEBUG /DDETAILED_MEMORY_TRACKING /MDd /ZI /Ob0 /Od /RTC1" CACHE STRING "c++ debug with memory tracking compiler flags" FORCE)
set(CMAKE_CXX_FLAGS_GCC "/DMSVC /W4 /WX /Zc:wchar_t- /GR /EHsc" CACHE STRING "c++ gcc (release) compiler flags" FORCE)
set(CMAKE_C_FLAGS "/DMSVC /W4 /WX" CACHE STRING "c compiler flags" FORCE)
set(CMAKE_C_FLAGS_DEBUG "/D_DEBUG /MDd /ZI /Ob0 /Od /RTC1" CACHE STRING "c debug compiler flags" FORCE)
set(CMAKE_C_FLAGS_DEBUGWITHMEMORYTRACKING "/D_DEBUG /DDETAILED_MEMORY_TRACKING /MDd /ZI /Ob0 /Od /RTC1" CACHE STRING "c debug with memory tracking compiler flags" FORCE)
set(CMAKE_C_FLAGS_GCC "/DMSVC /W4 /WX" CACHE STRING "c gcc (release) compiler flags" FORCE)
SET(CMAKE_EXE_LINKER_FLAGS_DEBUGWITHMEMORYTRACKING "/DEBUG" CACHE STRING "Flags used for linking binaries during debug with memory tracking builds." FORCE)
SET(CMAKE_EXE_LINKER_FLAGS_GCC "/INCREMENTAL:NO" CACHE STRING "Flags used for linking binaries during gcc (release) builds." FORCE)
SET(CMAKE_SHARED_LINKER_FLAGS_DEBUGWITHMEMORYTRACKING "/DEBUG" CACHE STRING "Flags used by the shared libraries linker during debug with memory tracking builds." FORCE )
SET(CMAKE_SHARED_LINKER_FLAGS_GCC "/INCREMENTAL:NO" CACHE STRING "Flags used by the shared libraries linker during gcc (release) builds." FORCE )

set(ROOT_DIR "../../")
set(BIN_FOLDER "win64/vc++" CACHE STRING "")
set(SOLUTION_PLATFORM "win64/vc++" CACHE PATH "")

set(PHI_INCLUDE_DIRS "${ROOT_DIR}src/" CACHE PATH "")
set(PHI_TESTS_INCLUDE_DIRS "${ROOT_DIR}tests/" CACHE PATH "")
set(INCLUDE_DIRS "${ROOT_DIR}inc/" CACHE PATH "")
set(FREETYPE_INCLUDE_DIR_freetype2 "${ROOT_DIR}inc/freetype" CACHE PATH "")
set(FREETYPE_INCLUDE_DIR_ft2build "${ROOT_DIR}inc/freetype" CACHE PATH "")
set(FREEIMAGE_INCLUDE_DIRS "${ROOT_DIR}inc/freeimage" CACHE PATH "")
set(GLEW_INCLUDE_DIR "${ROOT_DIR}inc/gl" CACHE PATH "")
set(BULLET_INCLUDE_DIR "${ROOT_DIR}inc/bullet" CACHE PATH "")
set(GTEST_INCLUDE_DIR "${ROOT_DIR}inc/gtest" CACHE PATH "")

set(LIBS_DIRS "${CMAKE_SOURCE_DIR}/../../libs/win64/vc++" CACHE PATH "")
set(FREETYPE_LIBRARY optimized "freetype" debug "freetyped" CACHE PATH "")
set(FREEIMAGE_LIBRARY optimized "freeimage" debug "freeimaged" CACHE PATH "")
set(LIBICONV_LIBRARY optimized "libiconv" debug "libiconvd" CACHE PATH "")
set(LIBINTL_LIBRARY optimized "libintl" debug "libintld" CACHE PATH "")
set(GTEST_LIBRARY optimized "gtest" debug "gtestd" CACHE PATH "")
set(GLEW_LIBRARY optimized "glew32" debug "glew32d" CACHE PATH "")
set(GLSLANG_LIBRARY optimized "glslang" debug "glslang" CACHE PATH "")
set(GLSLANG_OSDEPENDENT_LIBRARY optimized "OSDependent" debug "OSDependent" CACHE PATH "")
set(GLSLANG_OGLCOMPILER_LIBRARY optimized "OGLCompiler" debug "OGLCompiler" CACHE PATH "")
set(GLSLANG_HLSL_LIBRARY optimized "HLSL" debug "HLSL" CACHE PATH "")

set(PHYSX_LIBRARY optimized "PhysX3" debug "PhysX3d" CACHE PATH "")
set(PHYSX_COMMON_LIBRARY optimized "PhysX3Common" debug "PhysX3Commond" CACHE PATH "")
set(PHYSX_EXTENSIONS_LIBRARY optimized "PhysX3Extensions" debug "PhysX3Extensionsd" CACHE PATH "")
set(PHYSX_PROFILESDK_LIBRARY optimized "PhysXProfileSDK" debug "PhysXProfileSDKd" CACHE PATH "")
set(ASSIMP_LIBRARY optimized "assimp" debug "assimpd" CACHE PATH "")